pipeline {
    agent any
    stages {
        stage('Build Application'){
            steps{
                echo "We are building java application"
                sh 'mvn -f jenkins/java-tomcat-sample/pom.xml clean package'
            }

            post{
                success{
                    echo "Archieving the artifacts..."
                    archiveArtifacts artifacts: '**/*.war', followSymlinks: false
                }
            }
        }
        stage('Deploy to Stagging'){
            steps{
                build "DeployToStagging"
                build job: "DeployToStagging"
            }
        }
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'MINUTES'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build "DeployToProduction"
                build job: "DeployToProduction"
            }
        }
    }
}
