pipeline {
    agent any
    stages {
        stage('Build Application'){
            steps{
                echo "We are building java application"
                sh 'mvn -f jenkins/java-tomcat-sample/pom.xml clean package'
            }

            post{
                success{
                    echo "Archieving the artifacts..."
                    archiveArtifacts artifacts: '**/*.war', followSymlinks: false
                }
            }
        }
        stage('Deploy to Stagging'){
            steps{
                copyArtifacts filter: '**/*.war', fingerprintArtifacts: true, projectName: env.JOB_NAME, selector: specific(env.BUILD_NUMBER)
                build "DeployToStagging"
                build job: "DeployToStagging"
            }
        }
    }
}
